import React,{useState,useEffect} from 'react';
import Card from '@material-ui/core/Card';
import CardActions from '@material-ui/core/CardActions';
import CardContent from '@material-ui/core/CardContent';
import Typography from '@material-ui/core/Typography';
import CircularProgress from '@material-ui/core/CircularProgress';
import Grid from '@material-ui/core/Grid';
import { useStyles } from '../UI/Theme';
import PositionGrid from './PositionsGrid';
const responseDetails ={
  "finance": {
      "result": [
          {
              "userId": "X3NJ2A7VDSABUI4URBWME2PZNM",
              "userIdType": "GUID",
              "portfolios": [
                  {
                      "userId": "X3NJ2A7VDSABUI4URBWME2PZNM",
                      "pfId": "the_berkshire_hathaway_portfolio",
                      "pfVersionId": 3316,
                      "sortOrder": 34,
                      "pfName": "The Berkshire Hathaway Portfolio",
                      "baseCurrency": "USD",
                      "slug": "the-berkshire-hathaway-portfolio",
                      "cashCurrency": "USD",
                      "consolidateLots": false,
                      "defaultPf": false,
                      "following": false,
                      "originDate": 1476072000000,
                      "creationDate": 1476297902614,
                      "lastUpdated": 1626221306159,
                      "positions": [
                          {
                              "posId": "pos_26113",
                              "symbol": "V",
                              "sortOrder": 0,
                              "lots": [
                                  {
                                      "lotId": "lot_25991",
                                      "sortOrder": 0,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 237.869995,
                                      "quantity": 0.210199
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26114",
                              "symbol": "JNJ",
                              "sortOrder": 1,
                              "lots": [
                                  {
                                      "lotId": "lot_25992",
                                      "sortOrder": 1,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 169.479996,
                                      "quantity": 0.29502
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26115",
                              "symbol": "MA",
                              "sortOrder": 2,
                              "lots": [
                                  {
                                      "lotId": "lot_25993",
                                      "sortOrder": 2,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 375.559998,
                                      "quantity": 0.133135
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26117",
                              "symbol": "PG",
                              "sortOrder": 3,
                              "lots": [
                                  {
                                      "lotId": "lot_25995",
                                      "sortOrder": 4,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 137.139999,
                                      "quantity": 0.364591
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26116",
                              "symbol": "BAC",
                              "sortOrder": 4,
                              "lots": [
                                  {
                                      "lotId": "lot_25994",
                                      "sortOrder": 3,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 40.630001,
                                      "quantity": 1.230618
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26118",
                              "symbol": "KO",
                              "sortOrder": 5,
                              "lots": [
                                  {
                                      "lotId": "lot_25996",
                                      "sortOrder": 5,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 54.48,
                                      "quantity": 0.917768
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26119",
                              "symbol": "VZ",
                              "sortOrder": 6,
                              "lots": [
                                  {
                                      "lotId": "lot_25997",
                                      "sortOrder": 6,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 56.150002,
                                      "quantity": 0.890472
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26120",
                              "symbol": "CVX",
                              "sortOrder": 7,
                              "lots": [
                                  {
                                      "lotId": "lot_25998",
                                      "sortOrder": 7,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 104.279999,
                                      "quantity": 0.479478
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26121",
                              "symbol": "MRK",
                              "sortOrder": 8,
                              "lots": [
                                  {
                                      "lotId": "lot_25999",
                                      "sortOrder": 8,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 77.550003,
                                      "quantity": 0.644745
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26122",
                              "symbol": "BMY",
                              "sortOrder": 9,
                              "lots": [
                                  {
                                      "lotId": "lot_26000",
                                      "sortOrder": 9,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 67.5,
                                      "quantity": 0.740741
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26123",
                              "symbol": "AXP",
                              "sortOrder": 10,
                              "lots": [
                                  {
                                      "lotId": "lot_26001",
                                      "sortOrder": 10,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 173.600006,
                                      "quantity": 0.288018
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26124",
                              "symbol": "USB",
                              "sortOrder": 11,
                              "lots": [
                                  {
                                      "lotId": "lot_26002",
                                      "sortOrder": 11,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 57.580002,
                                      "quantity": 0.868357
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26125",
                              "symbol": "SNOW",
                              "sortOrder": 12,
                              "lots": [
                                  {
                                      "lotId": "lot_26003",
                                      "sortOrder": 12,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 267.059998,
                                      "quantity": 0.187224
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26126",
                              "symbol": "MMC",
                              "sortOrder": 13,
                              "lots": [
                                  {
                                      "lotId": "lot_26004",
                                      "sortOrder": 13,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 141.830002,
                                      "quantity": 0.352535
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26127",
                              "symbol": "MCO",
                              "sortOrder": 14,
                              "lots": [
                                  {
                                      "lotId": "lot_26005",
                                      "sortOrder": 14,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 375.040009,
                                      "quantity": 0.133319
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26128",
                              "symbol": "AON",
                              "sortOrder": 15,
                              "lots": [
                                  {
                                      "lotId": "lot_26006",
                                      "sortOrder": 15,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 232.789993,
                                      "quantity": 0.214786
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26129",
                              "symbol": "KR",
                              "sortOrder": 16,
                              "lots": [
                                  {
                                      "lotId": "lot_26007",
                                      "sortOrder": 16,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 38.310001,
                                      "quantity": 1.305142
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26130",
                              "symbol": "RH",
                              "sortOrder": 17,
                              "lots": [
                                  {
                                      "lotId": "lot_26008",
                                      "sortOrder": 17,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 713.52002,
                                      "quantity": 0.070075
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26131",
                              "symbol": "GL",
                              "sortOrder": 18,
                              "lots": [
                                  {
                                      "lotId": "lot_26009",
                                      "sortOrder": 18,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 94.5,
                                      "quantity": 0.529101
                                  }
                              ]
                          },
                          {
                              "posId": "pos_26132",
                              "symbol": "AXTA",
                              "sortOrder": 19,
                              "lots": [
                                  {
                                      "lotId": "lot_26010",
                                      "sortOrder": 19,
                                      "tradeDate": "20210714",
                                      "purchasePrice": 30.43,
                                      "quantity": 1.643115
                                  }
                              ]
                          }
                      ],
                      "portfolioMeta": {
                          "privacy": "PUBLIC",
                          "portfolioDescription": "<p>Follow this list to discover and track stocks held by Berkshire Hathaway, the holding company of Warren Buffett.</p>\n<p><em>Background</em><p>Berkshire Hathaway, a multinational conglomerate based in the US, is led by Warren Buffett, who's arguably the nation's most revered investor. Dubbed the \"Oracle of Omaha\" Buffett's known for playing the long game in the stock market. Berkshire wholly owns a handful of companies and also owns stock in the companies listed here.</p><em>How did we choose these stocks?</em><p>Yahoo Finance employs sophisticated algorithms to monitor and detect trends in the Global Financial Markets. We bring these insights to you in the form of watchlists.</p><p>Find other winning investment ideas with the <a href=https://finance.yahoo.com/screener/new>Yahoo Finance Screener</a>.</p><em>How are these weighted?</em><p>The stocks in this watchlist are weighted equally.</p></p>",
                          "shortDescription": "Follow this list to discover and track stocks held by Berkshire Hathaway, the holding company of Warren Buffett.",
                          "followerCount": 195447,
                          "messageBoardId": "fin.pf.X3NJ2A7VDSABUI4URBWME2PZNM.GUID.the_berkshire_hathaway_portfolio.en",
                          "shareUrl": "https://finance.yahoo.com/u/yahoo-finance/watchlists/the-berkshire-hathaway-portfolio",
                          "backgroundImages": {
                              "header": {
                                  "url": "https://s.yimg.com/lo/api/res/1.2/hnTVlpwfYEputwh0gkd84Q--/cT05MDtmaT1maWxsO2FwcGlkPXl2aWRlb2ZlZWRzO3c9MTY1O2g9MTY1Ow--/https://s.yimg.com/dh/ap/default/161012/the-berkshire-hathaway-portfolio.jpg",
                                  "width": 165,
                                  "height": 165
                              },
                              "hero": {
                                  "url": "https://s.yimg.com/lo/api/res/1.2/DLyL4oyGiYBGUPC.KRp9wg--/cT05MDtmaT1maWxsO2FwcGlkPXl2aWRlb2ZlZWRzO3c9MzYwO2g9MjYwOw--/https://s.yimg.com/dh/ap/default/161012/the-berkshire-hathaway-portfolio.jpg",
                                  "width": 360,
                                  "height": 260
                              },
                              "card": {
                                  "url": "https://s.yimg.com/lo/api/res/1.2/UdZqmZxRVYLw5nx_u.rUSQ--/cT05MDtmaT1maWxsO2FwcGlkPXl2aWRlb2ZlZWRzO3c9MTc3O2g9MTUwOw--/https://s.yimg.com/dh/ap/default/161012/the-berkshire-hathaway-portfolio.jpg",
                                  "width": 177,
                                  "height": 150
                              }
                          },
                          "brand": {
                              "name": "yahoo finance",
                              "displayName": "Yahoo Finance",
                              "url": "https://finance.yahoo.com/",
                              "slug": "yahoo-finance",
                              "logoUrl": "https://s.yimg.com/dh/ap/finance/portfolio/yahoo-finance-logo-new.png"
                          }
                      },
                      "isMine": false
                  }
              ],
              "quotes": {
                  "AON": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Aon plc",
                      "fullExchangeName": "NYSE",
                      "longName": "Aon plc",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 1762998,
                      "averageDailyVolume10Day": 1243766,
                      "fiftyTwoWeekLowChange": 50.17,
                      "fiftyTwoWeekLowChangePercent": 0.27946746,
                      "fiftyTwoWeekRange": "179.52 - 260.97",
                      "fiftyTwoWeekHighChange": -31.279999,
                      "fiftyTwoWeekHighChangePercent": -0.119860515,
                      "fiftyTwoWeekLow": 179.52,
                      "fiftyTwoWeekHigh": 260.97,
                      "dividendDate": 1620950400,
                      "earningsTimestamp": 1627624800,
                      "earningsTimestampStart": 1627624800,
                      "earningsTimestampEnd": 1627624800,
                      "trailingAnnualDividendRate": 1.8,
                      "trailingPE": 25.182545,
                      "trailingAnnualDividendYield": 0.0077706785,
                      "epsTrailingTwelveMonths": 9.121,
                      "epsForward": 12.52,
                      "epsCurrentYear": 11.22,
                      "priceEpsCurrentYear": 20.47148,
                      "sharesOutstanding": 225647008,
                      "bookValue": 18.833,
                      "fiftyDayAverage": 243.08177,
                      "fiftyDayAverageChange": -13.391769,
                      "fiftyDayAverageChangePercent": -0.055091623,
                      "twoHundredDayAverage": 231.96074,
                      "twoHundredDayAverageChange": -2.2707367,
                      "twoHundredDayAverageChangePercent": -0.009789315,
                      "marketCap": 51828862976,
                      "market": "us_market",
                      "regularMarketPrice": 229.69,
                      "regularMarketTime": 1626276071,
                      "regularMarketChange": -1.949997,
                      "regularMarketOpen": 231.96,
                      "regularMarketDayHigh": 232.67,
                      "regularMarketDayLow": 229.26,
                      "regularMarketVolume": 286765,
                      "priceHint": 2,
                      "regularMarketChangePercent": -0.8418222,
                      "regularMarketDayRange": "229.26 - 232.67",
                      "regularMarketPreviousClose": 231.64,
                      "bid": 229.56,
                      "ask": 229.84,
                      "bidSize": 11,
                      "askSize": 10,
                      "messageBoardId": "finmb_119853",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 18.345846,
                      "priceToBook": 12.196145,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "AON"
                  },
                  "MMC": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Marsh & McLennan Companies, Inc",
                      "fullExchangeName": "NYSE",
                      "longName": "Marsh & McLennan Companies, Inc.",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 1831236,
                      "averageDailyVolume10Day": 1997483,
                      "fiftyTwoWeekLowChange": 38.770004,
                      "fiftyTwoWeekLowChangePercent": 0.37968862,
                      "fiftyTwoWeekRange": "102.11 - 142.94",
                      "fiftyTwoWeekHighChange": -2.0599976,
                      "fiftyTwoWeekHighChangePercent": -0.014411624,
                      "fiftyTwoWeekLow": 102.11,
                      "fiftyTwoWeekHigh": 142.94,
                      "dividendDate": 1620950400,
                      "earningsTimestamp": 1626957000,
                      "earningsTimestampStart": 1626957000,
                      "earningsTimestampEnd": 1626957000,
                      "trailingAnnualDividendRate": 1.86,
                      "trailingPE": 32.201145,
                      "trailingAnnualDividendYield": 0.013186813,
                      "epsTrailingTwelveMonths": 4.375,
                      "epsForward": 6.14,
                      "epsCurrentYear": 5.63,
                      "priceEpsCurrentYear": 25.02309,
                      "sharesOutstanding": 508532000,
                      "bookValue": 18.543,
                      "fiftyDayAverage": 139.20529,
                      "fiftyDayAverageChange": 1.6747131,
                      "fiftyDayAverageChangePercent": 0.012030528,
                      "twoHundredDayAverage": 125.52206,
                      "twoHundredDayAverageChange": 15.357948,
                      "twoHundredDayAverageChangePercent": 0.122352585,
                      "marketCap": 71641989120,
                      "market": "us_market",
                      "regularMarketPrice": 140.88,
                      "regularMarketTime": 1626276067,
                      "regularMarketChange": -0.16999817,
                      "regularMarketOpen": 140.68,
                      "regularMarketDayHigh": 141.07,
                      "regularMarketDayLow": 139.93,
                      "regularMarketVolume": 384654,
                      "priceHint": 2,
                      "regularMarketChangePercent": -0.12052333,
                      "regularMarketDayRange": "139.93 - 141.07",
                      "regularMarketPreviousClose": 141.05,
                      "bid": 140.87,
                      "ask": 140.9,
                      "bidSize": 8,
                      "askSize": 8,
                      "messageBoardId": "finmb_473342",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 22.944626,
                      "priceToBook": 7.5974765,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "MMC"
                  },
                  "BAC": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Bank of America Corporation",
                      "fullExchangeName": "NYSE",
                      "longName": "Bank of America Corporation",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 44359676,
                      "averageDailyVolume10Day": 47446916,
                      "fiftyTwoWeekLowChange": 15.104099,
                      "fiftyTwoWeekLowChangePercent": 0.65813065,
                      "fiftyTwoWeekRange": "22.95 - 43.49",
                      "fiftyTwoWeekHighChange": -5.4359016,
                      "fiftyTwoWeekHighChangePercent": -0.12499198,
                      "fiftyTwoWeekLow": 22.95,
                      "fiftyTwoWeekHigh": 43.49,
                      "dividendDate": 1624579200,
                      "earningsTimestamp": 1626265800,
                      "earningsTimestampStart": 1626265800,
                      "earningsTimestampEnd": 1626265800,
                      "trailingAnnualDividendRate": 0.72,
                      "trailingPE": 16.332232,
                      "trailingAnnualDividendYield": 0.018063221,
                      "epsTrailingTwelveMonths": 2.33,
                      "epsForward": 3.08,
                      "epsCurrentYear": 3.05,
                      "priceEpsCurrentYear": 12.476754,
                      "sharesOutstanding": 8569319936,
                      "bookValue": 29.067,
                      "fiftyDayAverage": 41.295883,
                      "fiftyDayAverageChange": -3.2417831,
                      "fiftyDayAverageChangePercent": -0.078501366,
                      "twoHundredDayAverage": 37.718163,
                      "twoHundredDayAverageChange": 0.3359375,
                      "twoHundredDayAverageChangePercent": 0.008906518,
                      "marketCap": 326097764352,
                      "market": "us_market",
                      "regularMarketPrice": 38.0541,
                      "regularMarketTime": 1626276072,
                      "regularMarketChange": -1.8059006,
                      "regularMarketOpen": 39.11,
                      "regularMarketDayHigh": 39.55,
                      "regularMarketDayLow": 37.86,
                      "regularMarketVolume": 49199818,
                      "priceHint": 2,
                      "regularMarketChangePercent": -4.5306087,
                      "regularMarketDayRange": "37.86 - 39.55",
                      "regularMarketPreviousClose": 39.86,
                      "bid": 37.9,
                      "ask": 37.91,
                      "bidSize": 32,
                      "askSize": 11,
                      "messageBoardId": "finmb_19049",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 12.355227,
                      "priceToBook": 1.3091857,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "BAC"
                  },
                  "KO": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Coca-Cola Company (The)",
                      "fullExchangeName": "NYSE",
                      "longName": "The Coca-Cola Company",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 14207068,
                      "averageDailyVolume10Day": 13783100,
                      "fiftyTwoWeekLowChange": 9.895,
                      "fiftyTwoWeekLowChangePercent": 0.21581244,
                      "fiftyTwoWeekRange": "45.85 - 56.48",
                      "fiftyTwoWeekHighChange": -0.7350006,
                      "fiftyTwoWeekHighChangePercent": -0.013013467,
                      "fiftyTwoWeekLow": 45.85,
                      "fiftyTwoWeekHigh": 56.48,
                      "dividendDate": 1625097600,
                      "earningsTimestamp": 1626870600,
                      "earningsTimestampStart": 1626870600,
                      "earningsTimestampEnd": 1626870600,
                      "trailingAnnualDividendRate": 1.65,
                      "trailingPE": 33.38024,
                      "trailingAnnualDividendYield": 0.029989094,
                      "epsTrailingTwelveMonths": 1.67,
                      "epsForward": 2.36,
                      "epsCurrentYear": 2.18,
                      "priceEpsCurrentYear": 25.5711,
                      "sharesOutstanding": 4311680000,
                      "bookValue": 4.722,
                      "fiftyDayAverage": 54.860588,
                      "fiftyDayAverageChange": 0.88441086,
                      "fiftyDayAverageChangePercent": 0.01612106,
                      "twoHundredDayAverage": 52.572647,
                      "twoHundredDayAverageChange": 3.1723518,
                      "twoHundredDayAverageChangePercent": 0.060342252,
                      "marketCap": 240354590720,
                      "market": "us_market",
                      "regularMarketPrice": 55.745,
                      "regularMarketTime": 1626276072,
                      "regularMarketChange": 0.7249985,
                      "regularMarketOpen": 55.02,
                      "regularMarketDayHigh": 55.75,
                      "regularMarketDayLow": 54.96,
                      "regularMarketVolume": 4653436,
                      "priceHint": 2,
                      "regularMarketChangePercent": 1.3176999,
                      "regularMarketDayRange": "54.96 - 55.75",
                      "regularMarketPreviousClose": 55.02,
                      "bid": 55.62,
                      "ask": 55.63,
                      "bidSize": 22,
                      "askSize": 22,
                      "messageBoardId": "finmb_26642",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 23.620764,
                      "priceToBook": 11.805379,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "KO"
                  },
                  "VZ": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Verizon Communications Inc.",
                      "fullExchangeName": "NYSE",
                      "longName": "Verizon Communications Inc.",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 16231371,
                      "averageDailyVolume10Day": 14383833,
                      "fiftyTwoWeekLowChange": 2.511898,
                      "fiftyTwoWeekLowChangePercent": 0.046663534,
                      "fiftyTwoWeekRange": "53.83 - 61.95",
                      "fiftyTwoWeekHighChange": -5.608101,
                      "fiftyTwoWeekHighChangePercent": -0.090526246,
                      "fiftyTwoWeekLow": 53.83,
                      "fiftyTwoWeekHigh": 61.95,
                      "dividendDate": 1627862400,
                      "earningsTimestamp": 1626852600,
                      "earningsTimestampStart": 1626852600,
                      "earningsTimestampEnd": 1626852600,
                      "trailingAnnualDividendRate": 2.498,
                      "trailingPE": 12.350264,
                      "trailingAnnualDividendYield": 0.044535566,
                      "epsTrailingTwelveMonths": 4.562,
                      "epsForward": 5.19,
                      "epsCurrentYear": 5.12,
                      "priceEpsCurrentYear": 11.004277,
                      "sharesOutstanding": 4140069888,
                      "bookValue": 17.206,
                      "fiftyDayAverage": 56.52206,
                      "fiftyDayAverageChange": -0.18016052,
                      "fiftyDayAverageChangePercent": -0.0031874373,
                      "twoHundredDayAverage": 56.927574,
                      "twoHundredDayAverageChange": -0.5856743,
                      "twoHundredDayAverageChangePercent": -0.01028806,
                      "marketCap": 233259401216,
                      "market": "us_market",
                      "regularMarketPrice": 56.3419,
                      "regularMarketTime": 1626276074,
                      "regularMarketChange": 0.25189972,
                      "regularMarketOpen": 56.09,
                      "regularMarketDayHigh": 56.374,
                      "regularMarketDayLow": 56.0391,
                      "regularMarketVolume": 6284171,
                      "priceHint": 2,
                      "regularMarketChangePercent": 0.44909915,
                      "regularMarketDayRange": "56.0391 - 56.374",
                      "regularMarketPreviousClose": 56.09,
                      "bid": 56.24,
                      "ask": 56.25,
                      "bidSize": 9,
                      "askSize": 8,
                      "messageBoardId": "finmb_415798",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 10.855857,
                      "priceToBook": 3.2745497,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "VZ"
                  },
                  "CVX": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Chevron Corporation",
                      "fullExchangeName": "NYSE",
                      "longName": "Chevron Corporation",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 9774523,
                      "averageDailyVolume10Day": 8716783,
                      "fiftyTwoWeekLowChange": 38.074997,
                      "fiftyTwoWeekLowChangePercent": 0.5843308,
                      "fiftyTwoWeekRange": "65.16 - 113.11",
                      "fiftyTwoWeekHighChange": -9.875,
                      "fiftyTwoWeekHighChangePercent": -0.08730439,
                      "fiftyTwoWeekLow": 65.16,
                      "fiftyTwoWeekHigh": 113.11,
                      "dividendDate": 1623283200,
                      "earningsTimestamp": 1627648200,
                      "earningsTimestampStart": 1627648200,
                      "earningsTimestampEnd": 1627648200,
                      "trailingAnnualDividendRate": 5.16,
                      "trailingAnnualDividendYield": 0.0496488,
                      "epsTrailingTwelveMonths": -4.124,
                      "epsForward": 7.11,
                      "epsCurrentYear": 6.03,
                      "priceEpsCurrentYear": 17.120232,
                      "sharesOutstanding": 1928060032,
                      "bookValue": 68.405,
                      "fiftyDayAverage": 105.99735,
                      "fiftyDayAverageChange": -2.762352,
                      "fiftyDayAverageChangePercent": -0.026060576,
                      "twoHundredDayAverage": 101.326324,
                      "twoHundredDayAverageChange": 1.9086761,
                      "twoHundredDayAverageChangePercent": 0.018836923,
                      "marketCap": 199043284992,
                      "market": "us_market",
                      "regularMarketPrice": 103.235,
                      "regularMarketTime": 1626276071,
                      "regularMarketChange": -0.6949997,
                      "regularMarketOpen": 104.48,
                      "regularMarketDayHigh": 105.31,
                      "regularMarketDayLow": 103.15,
                      "regularMarketVolume": 2365594,
                      "priceHint": 2,
                      "regularMarketChangePercent": -0.66871905,
                      "regularMarketDayRange": "103.15 - 105.31",
                      "regularMarketPreviousClose": 103.93,
                      "bid": 103.23,
                      "ask": 103.22,
                      "bidSize": 8,
                      "askSize": 11,
                      "messageBoardId": "finmb_98506",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 14.5196905,
                      "priceToBook": 1.5091734,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "CVX"
                  },
                  "USB": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "U.S. Bancorp",
                      "fullExchangeName": "NYSE",
                      "longName": "U.S. Bancorp",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 6269709,
                      "averageDailyVolume10Day": 5056600,
                      "fiftyTwoWeekLowChange": 22.25,
                      "fiftyTwoWeekLowChangePercent": 0.651156,
                      "fiftyTwoWeekRange": "34.17 - 62.47",
                      "fiftyTwoWeekHighChange": -6.050003,
                      "fiftyTwoWeekHighChangePercent": -0.096846536,
                      "fiftyTwoWeekLow": 34.17,
                      "fiftyTwoWeekHigh": 62.47,
                      "dividendDate": 1626307200,
                      "earningsTimestamp": 1626352200,
                      "earningsTimestampStart": 1626352200,
                      "earningsTimestampEnd": 1626352200,
                      "trailingAnnualDividendRate": 1.68,
                      "trailingPE": 14.890471,
                      "trailingAnnualDividendYield": 0.029515108,
                      "epsTrailingTwelveMonths": 3.789,
                      "epsForward": 4.41,
                      "epsCurrentYear": 4.76,
                      "priceEpsCurrentYear": 11.852941,
                      "sharesOutstanding": 1489680000,
                      "bookValue": 30.534,
                      "fiftyDayAverage": 58.08794,
                      "fiftyDayAverageChange": -1.667942,
                      "fiftyDayAverageChangePercent": -0.028714085,
                      "twoHundredDayAverage": 54.275517,
                      "twoHundredDayAverageChange": 2.1444817,
                      "twoHundredDayAverageChangePercent": 0.039511032,
                      "marketCap": 84047740928,
                      "market": "us_market",
                      "regularMarketPrice": 56.42,
                      "regularMarketTime": 1626276067,
                      "regularMarketChange": -0.5,
                      "regularMarketOpen": 57.0,
                      "regularMarketDayHigh": 57.42,
                      "regularMarketDayLow": 56.25,
                      "regularMarketVolume": 1567685,
                      "priceHint": 2,
                      "regularMarketChangePercent": -0.8784259,
                      "regularMarketDayRange": "56.25 - 57.42",
                      "regularMarketPreviousClose": 56.92,
                      "bid": 56.25,
                      "ask": 56.27,
                      "bidSize": 9,
                      "askSize": 8,
                      "messageBoardId": "finmb_305304",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 12.793651,
                      "priceToBook": 1.8477762,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "USB"
                  },
                  "SNOW": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Snowflake Inc.",
                      "fullExchangeName": "NYSE",
                      "longName": "Snowflake Inc.",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 4268998,
                      "averageDailyVolume10Day": 5027166,
                      "fiftyTwoWeekLowChange": 72.42,
                      "fiftyTwoWeekLowChangePercent": 0.39207405,
                      "fiftyTwoWeekRange": "184.71 - 429.0",
                      "fiftyTwoWeekHighChange": -171.87,
                      "fiftyTwoWeekHighChangePercent": -0.40062937,
                      "fiftyTwoWeekLow": 184.71,
                      "fiftyTwoWeekHigh": 429.0,
                      "earningsTimestamp": 1622059200,
                      "earningsTimestampStart": 1622059200,
                      "earningsTimestampEnd": 1622059200,
                      "epsTrailingTwelveMonths": -3.229,
                      "epsForward": -0.52,
                      "epsCurrentYear": -0.59,
                      "priceEpsCurrentYear": -435.8136,
                      "sharesOutstanding": 296100000,
                      "bookValue": 16.763,
                      "fiftyDayAverage": 245.98529,
                      "fiftyDayAverageChange": 11.144714,
                      "fiftyDayAverageChangePercent": 0.045306426,
                      "twoHundredDayAverage": 251.01633,
                      "twoHundredDayAverageChange": 6.113678,
                      "twoHundredDayAverageChangePercent": 0.024355698,
                      "marketCap": 76136194048,
                      "market": "us_market",
                      "regularMarketPrice": 257.13,
                      "regularMarketTime": 1626276071,
                      "regularMarketChange": -7.48999,
                      "regularMarketOpen": 268.91,
                      "regularMarketDayHigh": 269.6765,
                      "regularMarketDayLow": 256.51,
                      "regularMarketVolume": 1017450,
                      "priceHint": 2,
                      "regularMarketChangePercent": -2.8304703,
                      "regularMarketDayRange": "256.51 - 269.6765",
                      "regularMarketPreviousClose": 264.62,
                      "bid": 259.7,
                      "ask": 260.32,
                      "bidSize": 11,
                      "askSize": 9,
                      "messageBoardId": "finmb_275004592",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": -494.4808,
                      "priceToBook": 15.33914,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "SNOW"
                  },
                  "GL": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Globe Life Inc.",
                      "fullExchangeName": "NYSE",
                      "longName": "Globe Life Inc.",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 412534,
                      "averageDailyVolume10Day": 446066,
                      "fiftyTwoWeekLowChange": 20.059998,
                      "fiftyTwoWeekLowChangePercent": 0.2728138,
                      "fiftyTwoWeekRange": "73.53 - 108.22",
                      "fiftyTwoWeekHighChange": -14.630005,
                      "fiftyTwoWeekHighChangePercent": -0.13518763,
                      "fiftyTwoWeekLow": 73.53,
                      "fiftyTwoWeekHigh": 108.22,
                      "dividendDate": 1627603200,
                      "earningsTimestamp": 1619035200,
                      "earningsTimestampStart": 1626778740,
                      "earningsTimestampEnd": 1627300800,
                      "trailingAnnualDividendRate": 0.69,
                      "trailingPE": 13.702782,
                      "trailingAnnualDividendYield": 0.0073349634,
                      "epsTrailingTwelveMonths": 6.83,
                      "epsForward": 7.61,
                      "epsCurrentYear": 7.29,
                      "priceEpsCurrentYear": 12.838134,
                      "sharesOutstanding": 103053000,
                      "bookValue": 67.431,
                      "fiftyDayAverage": 99.757355,
                      "fiftyDayAverageChange": -6.1673584,
                      "fiftyDayAverageChangePercent": -0.061823595,
                      "twoHundredDayAverage": 98.70147,
                      "twoHundredDayAverageChange": -5.111473,
                      "twoHundredDayAverageChangePercent": -0.051787205,
                      "marketCap": 9644730368,
                      "market": "us_market",
                      "regularMarketPrice": 93.59,
                      "regularMarketTime": 1626275815,
                      "regularMarketChange": -0.48000336,
                      "regularMarketOpen": 93.91,
                      "regularMarketDayHigh": 94.9,
                      "regularMarketDayLow": 93.51,
                      "regularMarketVolume": 62725,
                      "priceHint": 2,
                      "regularMarketChangePercent": -0.5102619,
                      "regularMarketDayRange": "93.51 - 94.9",
                      "regularMarketPreviousClose": 94.07,
                      "bid": 93.66,
                      "ask": 93.78,
                      "bidSize": 8,
                      "askSize": 10,
                      "messageBoardId": "finmb_308916",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 12.298291,
                      "priceToBook": 1.3879373,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "GL"
                  },
                  "JNJ": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Johnson & Johnson",
                      "fullExchangeName": "NYSE",
                      "longName": "Johnson & Johnson",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 6876123,
                      "averageDailyVolume10Day": 6133150,
                      "fiftyTwoWeekLowChange": 36.76001,
                      "fiftyTwoWeekLowChangePercent": 0.27504686,
                      "fiftyTwoWeekRange": "133.65 - 173.65",
                      "fiftyTwoWeekHighChange": -3.2399902,
                      "fiftyTwoWeekHighChangePercent": -0.018658165,
                      "fiftyTwoWeekLow": 133.65,
                      "fiftyTwoWeekHigh": 173.65,
                      "dividendDate": 1623110400,
                      "earningsTimestamp": 1626870600,
                      "earningsTimestampStart": 1626870600,
                      "earningsTimestampEnd": 1626870600,
                      "trailingAnnualDividendRate": 4.04,
                      "trailingPE": 30.102457,
                      "trailingAnnualDividendYield": 0.023867194,
                      "epsTrailingTwelveMonths": 5.661,
                      "epsForward": 10.42,
                      "epsCurrentYear": 9.52,
                      "priceEpsCurrentYear": 17.90021,
                      "sharesOutstanding": 2633400064,
                      "bookValue": 25.006,
                      "fiftyDayAverage": 166.13705,
                      "fiftyDayAverageChange": 4.272949,
                      "fiftyDayAverageChangePercent": 0.025719423,
                      "twoHundredDayAverage": 163.75743,
                      "twoHundredDayAverageChange": 6.6525726,
                      "twoHundredDayAverageChangePercent": 0.040624555,
                      "marketCap": 448757727232,
                      "market": "us_market",
                      "regularMarketPrice": 170.41,
                      "regularMarketTime": 1626276075,
                      "regularMarketChange": 1.1399994,
                      "regularMarketOpen": 170.0,
                      "regularMarketDayHigh": 170.515,
                      "regularMarketDayLow": 169.07,
                      "regularMarketVolume": 1351810,
                      "priceHint": 2,
                      "regularMarketChangePercent": 0.67347986,
                      "regularMarketDayRange": "169.07 - 170.515",
                      "regularMarketPreviousClose": 169.27,
                      "bid": 170.19,
                      "ask": 170.24,
                      "bidSize": 8,
                      "askSize": 9,
                      "messageBoardId": "finmb_139677",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 16.354126,
                      "priceToBook": 6.8147645,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "JNJ"
                  },
                  "MRK": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Merck & Company, Inc.",
                      "fullExchangeName": "NYSE",
                      "longName": "Merck & Co., Inc.",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 12483071,
                      "averageDailyVolume10Day": 7825816,
                      "fiftyTwoWeekLowChange": 9.01989,
                      "fiftyTwoWeekLowChangePercent": 0.13180208,
                      "fiftyTwoWeekRange": "68.43511 - 83.778625",
                      "fiftyTwoWeekHighChange": -6.3236237,
                      "fiftyTwoWeekHighChangePercent": -0.075480156,
                      "fiftyTwoWeekLow": 68.43511,
                      "fiftyTwoWeekHigh": 83.778625,
                      "dividendDate": 1625616000,
                      "earningsTimestamp": 1627561800,
                      "earningsTimestampStart": 1627561800,
                      "earningsTimestampEnd": 1627561800,
                      "trailingAnnualDividendRate": 2.48,
                      "trailingPE": 27.972193,
                      "trailingAnnualDividendYield": 0.031954646,
                      "epsTrailingTwelveMonths": 2.769,
                      "epsForward": 6.57,
                      "epsCurrentYear": 6.15,
                      "priceEpsCurrentYear": 12.594309,
                      "sharesOutstanding": 2532059904,
                      "bookValue": 10.645,
                      "fiftyDayAverage": 75.77505,
                      "fiftyDayAverageChange": 1.6799545,
                      "fiftyDayAverageChangePercent": 0.022170287,
                      "twoHundredDayAverage": 74.4083,
                      "twoHundredDayAverageChange": 3.0466995,
                      "twoHundredDayAverageChangePercent": 0.040945694,
                      "marketCap": 196120707072,
                      "market": "us_market",
                      "regularMarketPrice": 77.455,
                      "regularMarketTime": 1626276072,
                      "regularMarketChange": -0.15499878,
                      "regularMarketOpen": 77.6,
                      "regularMarketDayHigh": 77.71,
                      "regularMarketDayLow": 76.88,
                      "regularMarketVolume": 2071332,
                      "priceHint": 2,
                      "regularMarketChangePercent": -0.19971496,
                      "regularMarketDayRange": "76.88 - 77.71",
                      "regularMarketPreviousClose": 77.61,
                      "bid": 77.3,
                      "ask": 77.3,
                      "bidSize": 8,
                      "askSize": 9,
                      "messageBoardId": "finmb_288502",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 11.789193,
                      "priceToBook": 7.276186,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "MRK"
                  },
                  "KR": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Kroger Company (The)",
                      "fullExchangeName": "NYSE",
                      "longName": "The Kroger Co.",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 7697001,
                      "averageDailyVolume10Day": 5607500,
                      "fiftyTwoWeekLowChange": 7.949999,
                      "fiftyTwoWeekLowChangePercent": 0.26194394,
                      "fiftyTwoWeekRange": "30.35 - 42.99",
                      "fiftyTwoWeekHighChange": -4.6900024,
                      "fiftyTwoWeekHighChangePercent": -0.10909519,
                      "fiftyTwoWeekLow": 30.35,
                      "fiftyTwoWeekHigh": 42.99,
                      "dividendDate": 1630454400,
                      "earningsTimestamp": 1623916823,
                      "earningsTimestampStart": 1631190600,
                      "earningsTimestampEnd": 1631536200,
                      "trailingAnnualDividendRate": 0.72,
                      "trailingPE": 19.854847,
                      "trailingAnnualDividendYield": 0.01891253,
                      "epsTrailingTwelveMonths": 1.929,
                      "epsForward": 3.06,
                      "epsCurrentYear": 3.08,
                      "priceEpsCurrentYear": 12.435065,
                      "sharesOutstanding": 747238016,
                      "bookValue": 12.348,
                      "fiftyDayAverage": 38.27647,
                      "fiftyDayAverageChange": 0.023529053,
                      "fiftyDayAverageChangePercent": 6.1471324E-4,
                      "twoHundredDayAverage": 35.92243,
                      "twoHundredDayAverageChange": 2.377571,
                      "twoHundredDayAverageChangePercent": 0.06618626,
                      "marketCap": 28619214848,
                      "market": "us_market",
                      "regularMarketPrice": 38.3,
                      "regularMarketTime": 1626276071,
                      "regularMarketChange": 0.22999954,
                      "regularMarketOpen": 38.04,
                      "regularMarketDayHigh": 38.445,
                      "regularMarketDayLow": 37.92,
                      "regularMarketVolume": 1674807,
                      "priceHint": 2,
                      "regularMarketChangePercent": 0.60414904,
                      "regularMarketDayRange": "37.92 - 38.445",
                      "regularMarketPreviousClose": 38.07,
                      "bid": 38.4,
                      "ask": 38.41,
                      "bidSize": 10,
                      "askSize": 13,
                      "messageBoardId": "finmb_284342",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 12.51634,
                      "priceToBook": 3.101717,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "KR"
                  },
                  "BMY": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Bristol-Myers Squibb Company",
                      "fullExchangeName": "NYSE",
                      "longName": "Bristol-Myers Squibb Company",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 10052541,
                      "averageDailyVolume10Day": 8559033,
                      "fiftyTwoWeekLowChange": 10.964996,
                      "fiftyTwoWeekLowChangePercent": 0.19321579,
                      "fiftyTwoWeekRange": "56.75 - 67.96",
                      "fiftyTwoWeekHighChange": -0.24500275,
                      "fiftyTwoWeekHighChangePercent": -0.0036051022,
                      "fiftyTwoWeekLow": 56.75,
                      "fiftyTwoWeekHigh": 67.96,
                      "dividendDate": 1627862400,
                      "earningsTimestamp": 1627475400,
                      "earningsTimestampStart": 1627475400,
                      "earningsTimestampEnd": 1627475400,
                      "trailingAnnualDividendRate": 1.88,
                      "trailingAnnualDividendYield": 0.02787663,
                      "epsTrailingTwelveMonths": -2.764,
                      "epsForward": 8.03,
                      "epsCurrentYear": 7.46,
                      "priceEpsCurrentYear": 9.077077,
                      "sharesOutstanding": 2232839936,
                      "bookValue": 16.842,
                      "fiftyDayAverage": 66.28,
                      "fiftyDayAverageChange": 1.4349976,
                      "fiftyDayAverageChangePercent": 0.021650536,
                      "twoHundredDayAverage": 63.86625,
                      "twoHundredDayAverageChange": 3.8487473,
                      "twoHundredDayAverageChangePercent": 0.060262617,
                      "marketCap": 151196745728,
                      "market": "us_market",
                      "regularMarketPrice": 67.715,
                      "regularMarketTime": 1626276069,
                      "regularMarketChange": 0.2749939,
                      "regularMarketOpen": 67.53,
                      "regularMarketDayHigh": 67.77,
                      "regularMarketDayLow": 67.2,
                      "regularMarketVolume": 1652581,
                      "priceHint": 2,
                      "regularMarketChangePercent": 0.4077608,
                      "regularMarketDayRange": "67.2 - 67.77",
                      "regularMarketPreviousClose": 67.44,
                      "bid": 67.6,
                      "ask": 67.61,
                      "bidSize": 8,
                      "askSize": 8,
                      "messageBoardId": "finmb_25798",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 8.432752,
                      "priceToBook": 4.020603,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "BMY"
                  },
                  "MA": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Mastercard Incorporated",
                      "fullExchangeName": "NYSE",
                      "longName": "Mastercard Incorporated",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 3185223,
                      "averageDailyVolume10Day": 3156483,
                      "fiftyTwoWeekLowChange": 107.0491,
                      "fiftyTwoWeekLowChangePercent": 0.3806867,
                      "fiftyTwoWeekRange": "281.2 - 401.5",
                      "fiftyTwoWeekHighChange": -13.250885,
                      "fiftyTwoWeekHighChangePercent": -0.03300345,
                      "fiftyTwoWeekLow": 281.2,
                      "fiftyTwoWeekHigh": 401.5,
                      "dividendDate": 1628467200,
                      "earningsTimestamp": 1619699400,
                      "earningsTimestampStart": 1627475400,
                      "earningsTimestampEnd": 1627907400,
                      "trailingAnnualDividendRate": 1.68,
                      "trailingPE": 59.56568,
                      "trailingAnnualDividendYield": 0.0043783067,
                      "epsTrailingTwelveMonths": 6.518,
                      "epsForward": 10.44,
                      "epsCurrentYear": 7.86,
                      "priceEpsCurrentYear": 49.39556,
                      "sharesOutstanding": 982905024,
                      "bookValue": 6.378,
                      "fiftyDayAverage": 368.88678,
                      "fiftyDayAverageChange": 19.362335,
                      "fiftyDayAverageChangePercent": 0.052488558,
                      "twoHundredDayAverage": 361.0911,
                      "twoHundredDayAverageChange": 27.15802,
                      "twoHundredDayAverageChangePercent": 0.075210996,
                      "marketCap": 384773095424,
                      "market": "us_market",
                      "regularMarketPrice": 388.2491,
                      "regularMarketTime": 1626276066,
                      "regularMarketChange": 4.5391235,
                      "regularMarketOpen": 382.98,
                      "regularMarketDayHigh": 391.07,
                      "regularMarketDayLow": 383.415,
                      "regularMarketVolume": 1567951,
                      "priceHint": 2,
                      "regularMarketChangePercent": 1.1829568,
                      "regularMarketDayRange": "383.415 - 391.07",
                      "regularMarketPreviousClose": 383.71,
                      "bid": 387.66,
                      "ask": 387.89,
                      "bidSize": 11,
                      "askSize": 18,
                      "messageBoardId": "finmb_6477196",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 37.188614,
                      "priceToBook": 60.873177,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "MA"
                  },
                  "V": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Visa Inc.",
                      "fullExchangeName": "NYSE",
                      "longName": "Visa Inc.",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 6716990,
                      "averageDailyVolume10Day": 6584450,
                      "fiftyTwoWeekLowChange": 66.7,
                      "fiftyTwoWeekLowChangePercent": 0.3721475,
                      "fiftyTwoWeekRange": "179.23 - 245.93",
                      "fiftyTwoWeekHighChange": 0.0,
                      "fiftyTwoWeekHighChangePercent": 0.0,
                      "fiftyTwoWeekLow": 179.23,
                      "fiftyTwoWeekHigh": 245.93,
                      "dividendDate": 1622505600,
                      "earningsTimestamp": 1627416000,
                      "earningsTimestampStart": 1627416000,
                      "earningsTimestampEnd": 1627416000,
                      "trailingAnnualDividendRate": 1.26,
                      "trailingPE": 50.83299,
                      "trailingAnnualDividendYield": 0.005199092,
                      "epsTrailingTwelveMonths": 4.838,
                      "epsForward": 7.06,
                      "epsCurrentYear": 5.63,
                      "priceEpsCurrentYear": 43.682056,
                      "sharesOutstanding": 1691810048,
                      "bookValue": 16.084,
                      "fiftyDayAverage": 233.51852,
                      "fiftyDayAverageChange": 12.4114685,
                      "fiftyDayAverageChangePercent": 0.053149823,
                      "twoHundredDayAverage": 220.7019,
                      "twoHundredDayAverageChange": 25.228088,
                      "twoHundredDayAverageChangePercent": 0.11430843,
                      "marketCap": 541136945152,
                      "market": "us_market",
                      "regularMarketPrice": 245.93,
                      "regularMarketTime": 1626276064,
                      "regularMarketChange": 3.5799866,
                      "regularMarketOpen": 243.22,
                      "regularMarketDayHigh": 245.93,
                      "regularMarketDayLow": 242.82,
                      "regularMarketVolume": 2576451,
                      "priceHint": 2,
                      "regularMarketChangePercent": 1.4771968,
                      "regularMarketDayRange": "242.82 - 245.93",
                      "regularMarketPreviousClose": 242.35,
                      "bid": 245.34,
                      "ask": 245.38,
                      "bidSize": 8,
                      "askSize": 10,
                      "messageBoardId": "finmb_38043467",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 34.83428,
                      "priceToBook": 15.290351,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "V"
                  },
                  "RH": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "RH",
                      "fullExchangeName": "NYSE",
                      "longName": "RH",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 594858,
                      "averageDailyVolume10Day": 463283,
                      "fiftyTwoWeekLowChange": 432.41998,
                      "fiftyTwoWeekLowChangePercent": 1.6041101,
                      "fiftyTwoWeekRange": "269.57 - 733.05",
                      "fiftyTwoWeekHighChange": -31.059998,
                      "fiftyTwoWeekHighChangePercent": -0.04237091,
                      "fiftyTwoWeekLow": 269.57,
                      "fiftyTwoWeekHigh": 733.05,
                      "earningsTimestamp": 1623254700,
                      "earningsTimestampStart": 1631012340,
                      "earningsTimestampEnd": 1631534400,
                      "trailingPE": 52.383404,
                      "epsTrailingTwelveMonths": 13.401,
                      "epsForward": 25.15,
                      "epsCurrentYear": 22.68,
                      "priceEpsCurrentYear": 30.951939,
                      "sharesOutstanding": 21030400,
                      "bookValue": 28.28,
                      "fiftyDayAverage": 666.91943,
                      "fiftyDayAverageChange": 35.070557,
                      "fiftyDayAverageChangePercent": 0.052585896,
                      "twoHundredDayAverage": 576.38043,
                      "twoHundredDayAverageChange": 125.60956,
                      "twoHundredDayAverageChangePercent": 0.21792822,
                      "marketCap": 14763129856,
                      "market": "us_market",
                      "regularMarketPrice": 701.99,
                      "regularMarketTime": 1626275669,
                      "regularMarketChange": -6.340027,
                      "regularMarketOpen": 715.2,
                      "regularMarketDayHigh": 715.8112,
                      "regularMarketDayLow": 700.7,
                      "regularMarketVolume": 107107,
                      "priceHint": 2,
                      "regularMarketChangePercent": -0.8950668,
                      "regularMarketDayRange": "700.7 - 715.8112",
                      "regularMarketPreviousClose": 708.33,
                      "bid": 700.86,
                      "ask": 702.3,
                      "bidSize": 8,
                      "askSize": 10,
                      "messageBoardId": "finmb_53839639",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 27.912127,
                      "priceToBook": 24.822842,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "RH"
                  },
                  "PG": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Procter & Gamble Company (The)",
                      "fullExchangeName": "NYSE",
                      "longName": "The Procter & Gamble Company",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 8557982,
                      "averageDailyVolume10Day": 6335350,
                      "fiftyTwoWeekLowChange": 16.370003,
                      "fiftyTwoWeekLowChangePercent": 0.13468818,
                      "fiftyTwoWeekRange": "121.54 - 146.92",
                      "fiftyTwoWeekHighChange": -9.0099945,
                      "fiftyTwoWeekHighChangePercent": -0.061325856,
                      "fiftyTwoWeekLow": 121.54,
                      "fiftyTwoWeekHigh": 146.92,
                      "dividendDate": 1621209600,
                      "earningsTimestamp": 1627648200,
                      "earningsTimestampStart": 1627648200,
                      "earningsTimestampEnd": 1627648200,
                      "trailingAnnualDividendRate": 3.163,
                      "trailingPE": 25.355764,
                      "trailingAnnualDividendYield": 0.023092648,
                      "epsTrailingTwelveMonths": 5.439,
                      "epsForward": 5.93,
                      "epsCurrentYear": 5.63,
                      "priceEpsCurrentYear": 24.49556,
                      "sharesOutstanding": 2448229888,
                      "bookValue": 18.676,
                      "fiftyDayAverage": 135.10382,
                      "fiftyDayAverageChange": 2.8061829,
                      "fiftyDayAverageChangePercent": 0.020770567,
                      "twoHundredDayAverage": 133.30478,
                      "twoHundredDayAverageChange": 4.6052246,
                      "twoHundredDayAverageChangePercent": 0.034546584,
                      "marketCap": 337635377152,
                      "market": "us_market",
                      "regularMarketPrice": 137.91,
                      "regularMarketTime": 1626276060,
                      "regularMarketChange": 0.94000244,
                      "regularMarketOpen": 137.01,
                      "regularMarketDayHigh": 137.92,
                      "regularMarketDayLow": 136.39,
                      "regularMarketVolume": 1580351,
                      "priceHint": 2,
                      "regularMarketChangePercent": 0.68628347,
                      "regularMarketDayRange": "136.39 - 137.92",
                      "regularMarketPreviousClose": 136.97,
                      "bid": 137.71,
                      "ask": 137.72,
                      "bidSize": 9,
                      "askSize": 10,
                      "messageBoardId": "finmb_33328",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 23.256325,
                      "priceToBook": 7.3843436,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "PG"
                  },
                  "MCO": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Moody's Corporation",
                      "fullExchangeName": "NYSE",
                      "longName": "Moody's Corporation",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 669674,
                      "averageDailyVolume10Day": 513666,
                      "fiftyTwoWeekLowChange": 121.520004,
                      "fiftyTwoWeekLowChangePercent": 0.4799937,
                      "fiftyTwoWeekRange": "253.17 - 377.94",
                      "fiftyTwoWeekHighChange": -3.25,
                      "fiftyTwoWeekHighChangePercent": -0.008599249,
                      "fiftyTwoWeekLow": 253.17,
                      "fiftyTwoWeekHigh": 377.94,
                      "dividendDate": 1623283200,
                      "earningsTimestamp": 1627475400,
                      "earningsTimestampStart": 1627475400,
                      "earningsTimestampEnd": 1627475400,
                      "trailingAnnualDividendRate": 2.3,
                      "trailingPE": 34.965473,
                      "trailingAnnualDividendYield": 0.0061333333,
                      "epsTrailingTwelveMonths": 10.716,
                      "epsForward": 12.24,
                      "epsCurrentYear": 11.52,
                      "priceEpsCurrentYear": 32.525173,
                      "sharesOutstanding": 187200000,
                      "bookValue": 10.844,
                      "fiftyDayAverage": 352.60117,
                      "fiftyDayAverageChange": 22.088837,
                      "fiftyDayAverageChangePercent": 0.06264539,
                      "twoHundredDayAverage": 310.74808,
                      "twoHundredDayAverageChange": 63.941925,
                      "twoHundredDayAverageChangePercent": 0.20576772,
                      "marketCap": 70141968384,
                      "market": "us_market",
                      "regularMarketPrice": 374.69,
                      "regularMarketTime": 1626276011,
                      "regularMarketChange": -0.30999756,
                      "regularMarketOpen": 375.57,
                      "regularMarketDayHigh": 375.91,
                      "regularMarketDayLow": 373.66,
                      "regularMarketVolume": 91933,
                      "priceHint": 2,
                      "regularMarketChangePercent": -0.08266602,
                      "regularMarketDayRange": "373.66 - 375.91",
                      "regularMarketPreviousClose": 375.0,
                      "bid": 375.0,
                      "ask": 375.53,
                      "bidSize": 9,
                      "askSize": 9,
                      "messageBoardId": "finmb_528325",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 30.611929,
                      "priceToBook": 34.55275,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "MCO"
                  },
                  "AXP": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "American Express Company",
                      "fullExchangeName": "NYSE",
                      "longName": "American Express Company",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 3143346,
                      "averageDailyVolume10Day": 3719766,
                      "fiftyTwoWeekLowChange": 82.869995,
                      "fiftyTwoWeekLowChangePercent": 0.92997414,
                      "fiftyTwoWeekRange": "89.11 - 174.76",
                      "fiftyTwoWeekHighChange": -2.7799988,
                      "fiftyTwoWeekHighChangePercent": -0.015907524,
                      "fiftyTwoWeekLow": 89.11,
                      "fiftyTwoWeekHigh": 174.76,
                      "dividendDate": 1628553600,
                      "earningsTimestamp": 1627043400,
                      "earningsTimestampStart": 1627043400,
                      "earningsTimestampEnd": 1627043400,
                      "trailingAnnualDividendRate": 1.72,
                      "trailingPE": 28.188822,
                      "trailingAnnualDividendYield": 0.009964083,
                      "epsTrailingTwelveMonths": 6.101,
                      "epsForward": 9.19,
                      "epsCurrentYear": 7.54,
                      "priceEpsCurrentYear": 22.809017,
                      "sharesOutstanding": 803302976,
                      "bookValue": 30.447,
                      "fiftyDayAverage": 165.32823,
                      "fiftyDayAverageChange": 6.651764,
                      "fiftyDayAverageChangePercent": 0.040233683,
                      "twoHundredDayAverage": 145.33405,
                      "twoHundredDayAverageChange": 26.64595,
                      "twoHundredDayAverageChangePercent": 0.1833428,
                      "marketCap": 138152034304,
                      "market": "us_market",
                      "regularMarketPrice": 171.98,
                      "regularMarketTime": 1626276054,
                      "regularMarketChange": -0.6399994,
                      "regularMarketOpen": 172.86,
                      "regularMarketDayHigh": 174.5,
                      "regularMarketDayLow": 171.94,
                      "regularMarketVolume": 904294,
                      "priceHint": 2,
                      "regularMarketChangePercent": -0.37075624,
                      "regularMarketDayRange": "171.94 - 174.5",
                      "regularMarketPreviousClose": 172.62,
                      "bid": 172.05,
                      "ask": 172.14,
                      "bidSize": 8,
                      "askSize": 10,
                      "messageBoardId": "finmb_92001",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 18.71382,
                      "priceToBook": 5.648504,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "AXP"
                  },
                  "AXTA": {
                      "language": "en-US",
                      "region": "US",
                      "quoteType": "EQUITY",
                      "triggerable": true,
                      "quoteSourceName": "Nasdaq Real Time Price",
                      "currency": "USD",
                      "shortName": "Axalta Coating Systems Ltd.",
                      "fullExchangeName": "NYSE",
                      "longName": "Axalta Coating Systems Ltd.",
                      "financialCurrency": "USD",
                      "averageDailyVolume3Month": 3365604,
                      "averageDailyVolume10Day": 2492116,
                      "fiftyTwoWeekLowChange": 9.559999,
                      "fiftyTwoWeekLowChangePercent": 0.47209874,
                      "fiftyTwoWeekRange": "20.25 - 34.2",
                      "fiftyTwoWeekHighChange": -4.3900013,
                      "fiftyTwoWeekHighChangePercent": -0.12836261,
                      "fiftyTwoWeekLow": 20.25,
                      "fiftyTwoWeekHigh": 34.2,
                      "earningsTimestamp": 1619453705,
                      "earningsTimestampStart": 1627389000,
                      "earningsTimestampEnd": 1627907400,
                      "trailingPE": 82.80555,
                      "epsTrailingTwelveMonths": 0.36,
                      "epsForward": 2.32,
                      "epsCurrentYear": 2.06,
                      "priceEpsCurrentYear": 14.470874,
                      "sharesOutstanding": 232947008,
                      "bookValue": 5.839,
                      "fiftyDayAverage": 31.261177,
                      "fiftyDayAverageChange": -1.4511776,
                      "fiftyDayAverageChangePercent": -0.04642108,
                      "twoHundredDayAverage": 30.135,
                      "twoHundredDayAverageChange": -0.32500076,
                      "twoHundredDayAverageChangePercent": -0.010784827,
                      "marketCap": 6944150016,
                      "market": "us_market",
                      "regularMarketPrice": 29.81,
                      "regularMarketTime": 1626276071,
                      "regularMarketChange": 0.0,
                      "regularMarketOpen": 29.83,
                      "regularMarketDayHigh": 30.18,
                      "regularMarketDayLow": 29.705,
                      "regularMarketVolume": 396677,
                      "priceHint": 2,
                      "regularMarketChangePercent": 0.0,
                      "regularMarketDayRange": "29.705 - 30.18",
                      "regularMarketPreviousClose": 29.81,
                      "bid": 29.72,
                      "ask": 29.73,
                      "bidSize": 8,
                      "askSize": 8,
                      "messageBoardId": "finmb_216313883",
                      "marketState": "REGULAR",
                      "exchange": "NYQ",
                      "forwardPE": 12.849138,
                      "priceToBook": 5.105326,
                      "sourceInterval": 15,
                      "exchangeTimezoneName": "America/New_York",
                      "exchangeTimezoneShortName": "EDT",
                      "gmtOffSetMilliseconds": -14400000,
                      "esgPopulated": false,
                      "tradeable": false,
                      "exchangeDataDelayedBy": 0,
                      "symbol": "AXTA"
                  }
              }
          }
      ],
      "error": null
  }
}
const WatchListDetails = (props)=>{
    const [watchListItem,setWatchListItem]=useState();
    const classes = useStyles();
    useEffect(async ()=>{

      /** 
      const response = await fetch(
            'http://localhost:80/api/watchListPerformance?pfId='+props.pfId+'&userId='+props.userId,{
              headers: {
                  'Content-Type': 'application/json',
                  'Authorization':'Bearer '+localStorage.getItem("jwtToken")
                }
            }
          );
          if (!response.ok) {
            //throw new Error('Could not fetch watchlists!');
          
          }
   
          const data = await response.json();
  */
        const  data = {
            "finance": {
                "result": [
                    {
                        "portfolio": {
                            "oneDayPercentChange": -0.4978995778683476,
                            "oneMonthPercentChange": -3.97857,
                            "oneYearPercentChange": 8.13591,
                            "lifetimePercentChange": 24.0281,
                            "originTimestamp": 0,
                            "updatedAt": 1626275645
                        },
                        "symbols": {
                            "^GSPC": {
                                "oneDayPercentChange": 0.209,
                                "oneMonthPercentChange": 3.102,
                                "oneYearPercentChange": 35.697,
                                "lifetimePercentChange": 4607.892,
                                "originTimestamp": 0,
                                "updatedAt": 0
                            }
                        }
                    }
                ],
                "error": null
            }
        }
          console.log(data.finance);
    
          setWatchListItem(data.finance.result[0]);

    },[]);
    let details = <div style={{align:"center"}}><CircularProgress/></div>
    if(watchListItem){
        details = <div>
             <Grid container spacing={4} >
          <Grid item xs={4} sm={4} lg={4} spacing={4}>
          <Card className={classes.customCard}>
        <CardContent>
          <Typography  color="textSecondary" gutterBottom>
             Day %
          </Typography>
          
          <Typography variant="h5" component="h2">
           
          
            {watchListItem.portfolio.oneDayPercentChange.toFixed(2)}
          </Typography>
        </CardContent>
      
      </Card>
          </Grid>
          <Grid item xs={4} sm={4} lg={4}>
          <Card className={classes.customCard}>
        <CardContent>
          <Typography  color="textSecondary" gutterBottom>
             Month %
          </Typography>
          
          <Typography variant="h5" component="h2">
           
           
            {watchListItem.portfolio.oneMonthPercentChange.toFixed(2)}
          </Typography>
        </CardContent>
      
      </Card>
          </Grid>

          <Grid item xs={4} sm={4} lg={4}>
          <Card className={classes.customCard}>
        <CardContent>
          <Typography  color="textSecondary" gutterBottom>
             Year %
          </Typography>
          
          <Typography variant="h5" component="h2">
           
          
            {watchListItem.portfolio.oneYearPercentChange.toFixed(2)}
          </Typography>
        </CardContent>
      
      </Card>
          </Grid>
          <Grid item xs={12} sm={12} lg={12} spacing={4}>
<PositionGrid data={responseDetails}></PositionGrid>
              </Grid>
        </Grid>
        
     
        </div>
    }
    
    return (<div>
        {details}
    </div>);
}

export default WatchListDetails;
